INITIAL_STOCKS = [
    {
        "code": "603728",
        "name": "鸣志电器",
        "exchange": "SH",
        "industry_chain": "整机/系统集成",
        "industry_chain_detail": "空心杯电机、控制电机和运动控制系统",
        "core_products": "控制电机、驱动系统、运动控制解决方案",
        "supply_chain_tags": '["电机", "运动控制"]',
    },
    {
        "code": "002747",
        "name": "埃斯顿",
        "exchange": "SZ",
        "industry_chain": "整机/系统集成",
        "industry_chain_detail": "工业机器人和自动化系统集成",
        "core_products": "工业机器人、伺服系统、自动化产线",
        "supply_chain_tags": '["机器人本体", "系统集成"]',
    },
    {
        "code": "300124",
        "name": "汇川技术",
        "exchange": "SZ",
        "industry_chain": "减速器/伺服",
        "industry_chain_detail": "伺服驱动、控制器和工业自动化核心部件",
        "core_products": "伺服系统、控制器、工业自动化产品",
        "supply_chain_tags": '["伺服", "控制器"]',
    },
    {
        "code": "688017",
        "name": "绿的谐波",
        "exchange": "SH",
        "industry_chain": "核心零部件",
        "industry_chain_detail": "谐波减速器",
        "core_products": "谐波减速器、机电一体化执行器",
        "supply_chain_tags": '["谐波减速器", "执行器"]',
    },
    {
        "code": "002050",
        "name": "三花智控",
        "exchange": "SZ",
        "industry_chain": "核心零部件",
        "industry_chain_detail": "热管理和机器人执行器相关零部件",
        "core_products": "热管理部件、机电执行器部件",
        "supply_chain_tags": '["执行器", "热管理"]',
    },
    {
        "code": "688169",
        "name": "石头科技",
        "exchange": "SH",
        "industry_chain": "整机/系统集成",
        "industry_chain_detail": "服务机器人产品和智能感知应用",
        "core_products": "服务机器人、智能清洁机器人",
        "supply_chain_tags": '["服务机器人", "智能感知"]',
    },
    {
        "code": "603901",
        "name": "永创智能",
        "exchange": "SH",
        "industry_chain": "整机/系统集成",
        "industry_chain_detail": "智能装备和自动化系统",
        "core_products": "智能包装装备、自动化系统",
        "supply_chain_tags": '["智能装备", "自动化"]',
    },
    {
        "code": "688519",
        "name": "南芯科技",
        "exchange": "SH",
        "industry_chain": "传感器",
        "industry_chain_detail": "电源和模拟芯片",
        "core_products": "电源管理芯片、模拟芯片",
        "supply_chain_tags": '["芯片", "电源管理"]',
    },
    {
        "code": "002049",
        "name": "紫光国微",
        "exchange": "SZ",
        "industry_chain": "传感器",
        "industry_chain_detail": "特种集成电路和智能芯片",
        "core_products": "智能安全芯片、特种集成电路",
        "supply_chain_tags": '["芯片", "集成电路"]',
    },
    {
        "code": "300458",
        "name": "全志科技",
        "exchange": "SZ",
        "industry_chain": "传感器",
        "industry_chain_detail": "智能终端处理器和边缘计算芯片",
        "core_products": "SoC芯片、智能处理器",
        "supply_chain_tags": '["SoC", "边缘计算"]',
    },
    {
        "code": "688597",
        "name": "煜邦电力",
        "exchange": "SH",
        "industry_chain": "传感器",
        "industry_chain_detail": "智能感知和电力物联网设备",
        "core_products": "智能巡检、感知终端",
        "supply_chain_tags": '["智能感知", "巡检"]',
    },
    {
        "code": "603067",
        "name": "振华股份",
        "exchange": "SH",
        "industry_chain": "材料/结构件",
        "industry_chain_detail": "金属材料和化工材料",
        "core_products": "铬盐材料、精细化工材料",
        "supply_chain_tags": '["材料", "结构件"]',
    },
    {
        "code": "688787",
        "name": "海天瑞声",
        "exchange": "SH",
        "industry_chain": "软件/算法",
        "industry_chain_detail": "AI训练数据和语音数据服务",
        "core_products": "AI训练数据、语音识别数据集",
        "supply_chain_tags": '["AI数据", "语音识别"]',
    },
    {
        "code": "300418",
        "name": "昆仑万维",
        "exchange": "SZ",
        "industry_chain": "软件/算法",
        "industry_chain_detail": "AI大模型和应用软件",
        "core_products": "AI大模型、AIGC应用",
        "supply_chain_tags": '["AI大模型", "软件应用"]',
    },
    {
        "code": "002230",
        "name": "科大讯飞",
        "exchange": "SZ",
        "industry_chain": "软件/算法",
        "industry_chain_detail": "语音识别、认知智能和AI算法",
        "core_products": "语音识别、AI开放平台、大模型",
        "supply_chain_tags": '["语音识别", "AI算法"]',
    },
    {
        "code": "601615",
        "name": "明阳智能",
        "exchange": "SH",
        "industry_chain": "材料/结构件",
        "industry_chain_detail": "大型装备制造和复合材料应用",
        "core_products": "大型装备结构件、复合材料应用",
        "supply_chain_tags": '["结构件", "复合材料"]',
    },
    {
        "code": "300735",
        "name": "光弘科技",
        "exchange": "SZ",
        "industry_chain": "材料/结构件",
        "industry_chain_detail": "电子制造服务和精密组装",
        "core_products": "电子制造服务、精密组装",
        "supply_chain_tags": '["EMS", "精密制造"]',
    },
    {
        "code": "002896",
        "name": "中大力德",
        "exchange": "SZ",
        "industry_chain": "减速器/伺服",
        "industry_chain_detail": "减速器、电机和驱动器",
        "core_products": "精密减速器、伺服电机、驱动器",
        "supply_chain_tags": '["减速器", "电机"]',
    },
    {
        "code": "002472",
        "name": "双环传动",
        "exchange": "SZ",
        "industry_chain": "减速器/伺服",
        "industry_chain_detail": "精密齿轮和传动系统",
        "core_products": "精密齿轮、传动部件",
        "supply_chain_tags": '["齿轮", "传动"]',
    },
    {
        "code": "688320",
        "name": "禾川科技",
        "exchange": "SH",
        "industry_chain": "减速器/伺服",
        "industry_chain_detail": "伺服系统和工业控制",
        "core_products": "伺服系统、PLC、工业控制产品",
        "supply_chain_tags": '["伺服", "工业控制"]',
    },
    {
        "code": "688322",
        "name": "奥比中光",
        "exchange": "SH",
        "industry_chain": "传感器",
        "industry_chain_detail": "3D视觉感知传感器",
        "core_products": "3D视觉传感器、深度相机",
        "supply_chain_tags": '["3D视觉", "传感器"]',
    },
    {
        "code": "002600",
        "name": "领益智造",
        "exchange": "SZ",
        "industry_chain": "材料/结构件",
        "industry_chain_detail": "精密功能件和结构件",
        "core_products": "精密结构件、功能件、模组",
        "supply_chain_tags": '["结构件", "精密制造"]',
    },
]
